# https://github.com/geerlingguy/ansible-role-jenkins/
---
- name: install jenkins
  become: yes
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
    # - role: geerlingguy.jenkins
