# https://github.com/geerlingguy/ansible-role-jenkins/
# https://www.digitalocean.com/community/tutorials/how-to-install-jenkins-on-ubuntu-16-04
---
- name: add jenkins trusted key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present
